apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-example
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: springboot-example
  template:
    metadata:
      labels:
        app: springboot-example
    spec:
      containers:
      - image:  {{ .Values.image.name }}:{{ .Values.image.tag }}
        name: springboot-example
        ports:
        - containerPort: 8080
        imagePullPolicy: {{ .Values.image.pullPolicy }}

  